### PR TITLE
Create Security Practices.md

### PR DESCRIPTION
**Pull request by disclosurez**
This is required I think.. would help a lot of servers.

### CODE REVIEW

**Comment by alexandre433** [comment]
Hello, thank you for your contribution, but there's already a set of security measures written on our Wiki, which also should be in the README instead of "hidden" on just the Wiki tab.

https://github.com/FusionGen/FusionGen/wiki/Useful-Information

**Comment by disclosurez** [comment]
> 
> 
> Hello, thank you for your contribution, but there's already a set of security measures written on our Wiki, which also should be in the README instead of "hidden" on just the Wiki tab.
> 
> https://github.com/FusionGen/FusionGen/wiki/Useful-Information

This is not explanatory, and does not cover everything I have mentioned.

**Comment by alexandre433** [comment]
I did not say it did, I said it had a set of security measures, I meant to give you the link so you could look at the information given in the Wiki, so that you could seperate what is already written there from what was missing.

**Comment by disclosurez** [comment]
> 
> 
> I did not say it did, I said it had a set of security measures, I meant to give you the link so you could look at the information given in the Wiki, so that you could seperate what is already written there from what was missing.

I think it needs to all be in one place under "Security", or atleast update the wiki with what I have mentioned.

**Comment by alexandre433** [comment]
I'd suggest adding the following for database users, there should be 1 user for characters and 1 user for world (if implemented, if not will be in the future) and both of them, since it's read only, should ONLY have SELECT and VIEW permissions, an sql file, to make it easier, should also be made for that.

For auth database, SELECT, VIEW, INSERT and UPDATE permissions, should be added.
For the fusiongen database, which is also outdated and some changes are needed for this to take effect, only SELECT, VIEW, INSERT, UPDATE permissions should be added.

Why not DELETE and DROP?
- This should never be added due to the information of a website being really usefull for any type of logs or backtrace we want to search for
- The missing "feature" here is a "soft delete" on the items of the database, there should be a way that we logically delete the items/rows of a table without really deleting them, so that the data is safe AND never deleted from the database, making all of the data stored and never deleted.

**Comment by disclosurez** [comment]
Can we come up with the SQL queries to apply for users that admins can create?

Thanks!

I.e. 

1 for shop mysql account
1 for database mysql account

**Comment by omghixd** [comment]
In my opinion SQL Queries wouldn't help people learn how to properly configure SOAP or RA. We need to ensure the guide is easily understood. This cannot be automated by us. We need to learn the average operator HOW to create the account and HOW to properly make it secure alongside with the connection.

**Comment by alexandre433** [comment]
SQL queries would help for making a user have only certain permissions

**Pull request merged**
