### PR TITLE
CDN actually is not deprecated

### PR DESCRIPTION
**Pull request by CraftedRO**
Implement back cdn function since its already in the installer and acp settings.
I did tested it , and it works fine .

### CODE REVIEW

**Comment by CraftedRO** [comment]
Probably we need more tests on this

**Comment by OMGhixD-OG** [comment]
Is there a lot of work remaining or is this ready for merge?

**Comment by CraftedRO** [comment]
Is ready , I did few more tests and now shoud be fine.

**Comment by OMGhixD-OG** [comment]
Alright, Thank you!

Merging and awaiting further testing from the community

//Merged

**Pull request merged**
