### PR TITLE
credentials length

### PR DESCRIPTION
**Pull request by CraftedRO**
https://github.com/FusionGen/FusionGEN/issues/164

### CODE REVIEW

**Comment by Err0r1** [comment]
6 characters are quite little
I don't know what to think of it..

**Comment by CraftedRO** [comment]
as you wish, maybe it's just my opinion but it feel strange 4 characters username allowed but 6 characters for password required idk

**Comment by Err0r1** [comment]
then it is better that we also set the username to 6 characters, I think a 4-character password is very weird

**Comment by CraftedRO** [comment]
ok I did some reseach and it seems passwords on battlenet are between 8–16 characters in length so we can let 6 - 16 (maybe we shoud also add a check for max password length).
and username idk we can let 4 but the max I think 24 is more than enough

**Comment by Err0r1** [comment]
Yeah, good idea
Battlenet also works with 6 character passwords (tested with TCPP 1-2 years ago)

**Pull request merged**
