### PR TITLE
Few updates

### PR DESCRIPTION
**Pull request by CraftedRO**
- Set UNIX_TIMESTAMP() function for default article page so now article date will corespond to installation date (tested).
- Updated few outdated discord links.
- Updated #Project Information code standard goal to current year.
- Deleted screenshot.jpg from /themes (it doesn't belong there).

### CODE REVIEW

**Comment by OMGhixD-OG** [comment]
Nice PR :)

**Comment by Err0r1** [comment]
Thanks for the PR!

Added it to the update.

I will close the PR because the current version is no longer actively developed (the update takes too much time to develop 2 versions)

**Comment by CraftedRO** [comment]
So what version is now "actively developed" ?

**Comment by Err0r1** [comment]
The update
There is still enough to do and not much time atm, that's why I'm not doing anything on the current version

**Comment by Err0r1** [comment]
The update
There is still enough to do and not much time atm, that's why I'm not doing anything on the current version

**Comment by Err0r1** [comment]
The update
There is still enough to do and not much time atm, that's why I'm not doing anything on the current version

**Comment by CraftedRO** [comment]
So you basically turned this project off .
Gz and good luck finding time to self-update the whole cms then.

**Comment by Err0r1** [comment]
The CMS is already updated
What do you think I'm doing?

I didn't turn it off

Why should I work on 2 projects at the same time when I don't have much time anyway? That it takes even longer?

I just have very little time at the moment to work through the todo
I won't release the update until it's finished because I know that no one will ever update the CMS then

**Comment by CraftedRO** [comment]
That's not our job that ppl are too lazy to update they'r cms or some of them actually prefer to use old enough fusion versions.
But about projects you shoud just port and work for srp6 version in my opinion however.

**Comment by CraftedRO** [comment]
That's not our job that ppl are too lazy to update their cms or some of them actually prefer to use old enough fusion versions.
But about projects you shoud just port and work for srp6 version in my opinion however.

**Comment by Err0r1** [comment]
Fusion was designed to be compatible with all versions and I want to keep that, even if it means more work
I do it with pleasure
There are idiots who threaten fusion contributors
Maybe they see a real threat in it

Some have seen my internal todo list and know what massive improvements are coming

**Pull request closed without merging**
