### PR TITLE
Complement Fix: Character.php

### PR DESCRIPTION
**Pull request by htc16**

### CODE REVIEW

**Comment by CraftedRO** [comment]
can you explain us what do you want to fix ?

**Comment by htc16** [comment]
this PR fixed 2 error messages, the first was the array conversion problem and the second error, when setting PlayerSave.Stats.MinLevel greater than 1, the missing "Unknown".

**Comment by CraftedRO** [comment]
I understand now but have you tested if this PR will also display hunters focus if there is cata+ emulator case ?

**Comment by htc16** [comment]
sorry I don't have experience with any expansion other than LK.  I ended up correcting only the LK.

**Pull request closed without merging**
