### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by FrostbyteGR**

### CODE REVIEW

**Comment by OMGhixD-OG** [comment]
Thank you for the pull request. I'll need to review this more carefully myself first and i'd like to additionally bring in several UNIX folks to confirm or otherwise in regards to this PR.

Just because i dont know enough UNIX myself to make a proper call here.

Regardless, well done!

**Comment by Cillez** [comment]
Great installation guide. Only thing i would add is a little text to make users aware of the folder structure differences between the different systems (i.e usr/share & var/www). Other than that, I don't think I've ever seen a guide that is explained as good as this one in the pserver scene :D

**Comment by OMGhixD-OG** [comment]
> Great installation guide. Only thing i would add is a little text to make users aware of the folder structure differences between the different systems (i.e usr/share & var/www). Other than that, I don't think I've ever seen a guide that is explained as good as this one in the pserver scene :D

Thank you for your input and checking it for me 🥇

**Comment by OMGhixD-OG** [comment]
Merged :)

Thank you for your contribution @FrostbyteGR !

//Merged

**Pull request merged**
