### PR TITLE
Fix: Character.php

### PR DESCRIPTION
**Pull request by htc16**

### CODE REVIEW

**Comment by CraftedRO** [comment]
this PR broked wotlk hunter power bar, it won't be displayed at all

**Comment by htc16** [comment]
Oh, I'm sorry, I did this at dawn. I will upload update.

**Comment by CraftedRO** [comment]
hunters in wotlk does use mana as resource, please test any pr before submit

**Comment by Err0r1** [comment]
Its my fault, I haven't tested it
Since mop hunters use focus

**Comment by CraftedRO** [comment]
well since cata they use focus, but no sure what was the problem this pr intended to fix or for what emulator

**Pull request merged**
