### PR TITLE
Fix gm ticket answer from website via ingame mail on trinitycore

### PR DESCRIPTION
**Pull request by CraftedRO**
WoWScrnShot_040621_225051

### CODE REVIEW

**Comment by ErnestoGonzalezC** [comment]
Seems to work properly.

**Comment by OMGhixD-OG** [comment]
Yep! 

Good job @CraftedRO (Are you on our Discord BTW? I'd like to give you a contributor levelup for fantastic continued contribution :))

Nonetheless, thank you! Merging.

**Comment by CraftedRO** [comment]
thanks , this is just the beginning , I guess Il join disc later now im not feeling so healty irl :(

**Comment by OMGhixD-OG** [comment]
> thanks , this is just the beginning , I guess Il join disc later now im not feeling so healty irl :(

I'm sorry to hear. Feel better soon!

Looking forward to you joining the Community on Discord :)

**Pull request merged**
